version: "3"
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ralph_ng
      MYSQL_ROOT_PASSWORD: ralph_ng
      MYSQL_USER: ralph_ng
      MYSQL_PASSWORD: ralph_ng
    volumes:
      - ./volumes/static:/opt/static
      - ./volumes/media:/opt/media
      - ./volumes/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
  redis:
    image: redis:3.0
    ports:
      - "6379:6379"
  inkpy:
    image: ar4s/inkpy_jinja:latest
    restart: always
    links:
      - redis:redis
    env_file:
      - ./contrib/ralph.env
        
