site_name: Ralph Asset Management System
repo_url: https://github.com/allegro/ralph/

extra:
  social:
    - type: 'github'
      link: 'https://github.com/allegro/ralph'

nav:
  - Welcome: index.md
  - Installation guide:
      - Installation: installation/installation.md
      - Configuration: installation/configuration.md
      - 'Migration from Ralph 2.x': installation/data_migration.md
  - User guide:
      - Quickstart: user/quickstart.md
      - Advanced guide: user/guide.md
      - DCIM: user/dcim.md
      - Deployment: user/deployment.md
      - Domains management: user/domains.md
      - Custom fields: user/custom_fields.md
      - Dashboards: user/dashboards.md
      - API: user/api.md
      - ralph-cli: user/ralph-cli.md
      - DNS: user/dns.md
  - Developer guide:
      - Before you start: CONTRIBUTING.md
      - Architecture: development/overview.md
      - RalphAdmin: development/admin.md
      - Custom fields: development/custom_fields.md
      - Transitions: development/transitions.md
      - Addons : development/addons.md
      - Packaging: development/packaging.md
      - API: development/api.md
      - FAQ: development/faq.md

theme:
  name: material
  palette:
    primary: 'light blue'
    accent: 'indigo'

strict: true
dev_addr: 0.0.0.0:8000
markdown_extensions:
    - toc:
        permalink: True
extra_css:
    - custom.css
site_dir: /tmp/docs/_build/html  # sphinx compatible

